//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDBEntitiesAuto : DbContext
    {
        public LocalDBEntitiesAuto()
            : base("name=LocalDBEntitiesAuto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Samochod> Samochod { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenie { get; set; }
    }
}
