//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochod()
        {
            this.Wypozyczenie = new HashSet<Wypozyczenie>();
        }
    
        public int Id_Samochodu { get; set; }
        public Nullable<int> Id_Marki { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Rocznik { get; set; }
        public string Nadwozie { get; set; }
        public string Status { get; set; }
    
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie { get; set; }
    }
}
